name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: megamek
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: MegaMek
          repo: megamek
          excludes: prerelease, draft
    
      - uses: actions/checkout@v4
      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: tapenvyus/megamek
          dockerfile: Dockerfile
          build_args: MM_VERSION=${{ steps.megamek.outputs.release }}, SENTRY_ENABLED=true
          tags: latest, ${{ steps.megamek.outputs.release }}
