name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: megamek
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: MegaMek
          repo: megamek
          excludes: prerelease, draft
    
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build the Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            - MM_VERSION=${{ steps.megamek.outputs.release }}
            - SENTRY_ENABLED=true
          tags: tapenvyus/megamek:latest, tapenvyus/megamek:${{ steps.megamek.outputs.release }}
